/* eslint-disable @next/next/no-html-link-for-pages */
import { nav, notes, topics } from "./data";
import { ResearchSearch } from "./search-client";

function Header(){return <><div className="top-rule"/><header><a className="brand" href="/"><span className="monogram">ML</span><span><b>MAGAJI LAW</b><em>RESEARCH</em></span></a><nav>{nav.map(([n,h])=><a href={h} key={h}>{n}</a>)}</nav><a className="nav-cta" href="/commission-research">Commission research</a><details className="mobile-menu"><summary>Menu</summary><div>{nav.map(([n,h])=><a href={h} key={h}>{n}</a>)}<a href="/commission-research">Commission research</a></div></details></header></>}
function Footer(){return <footer><div><a className="brand inverse" href="/"><span className="monogram">ML</span><span><b>MAGAJI LAW</b><em>RESEARCH</em></span></a><p>A research and publishing division of Magaji Law.</p></div><div className="footer-links"><a href="/research-notes">Research Notes</a><a href="/methodology">Methodology</a><a href="/corrections">Corrections</a><a href="/disclaimer">Disclaimer</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div><div className="fineprint">© 2026 Magaji Law. All rights reserved.<br/>Research materials are for professional education and general information, not advice on any particular matter.</div></footer>}
function Shell({children}:{children:React.ReactNode}){return <><Header/><main>{children}</main><Footer/></>}
function Label({children}:{children:React.ReactNode}){return <span className="label">{children}</span>}
function NoteCard({index=0}:{index?:number}){const n=notes[index];return <a className="note-card" href={`/research-notes/${n.slug}`}><div className="card-top"><span>RESEARCH NOTE {String(n.issue).padStart(3,"0")}</span><span className={`status ${n.status.toLowerCase()}`}>{n.status}</span></div><h3>{n.title}</h3><p className="subtitle">{n.subtitle}</p><p>{n.abstract}</p><div className="labels">{n.labels.map(x=><Label key={x}>{x}</Label>)}</div><span className="read">{n.status==="Forthcoming"?"View preview":"Read the note"} →</span></a>}
function PageHero({eyebrow,title,dek}:{eyebrow:string,title:string,dek:string}){return <section className="page-hero"><div className="wrap narrow"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="dek">{dek}</p></div></section>}

function Home(){return <Shell>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">MAGAJI LAW RESEARCH</p><h1>What did the court <i>actually</i> decide?</h1><p>We examine Nigerian judicial authorities beyond the headline proposition—testing citations, separating ratio from obiter, tracing later treatment and identifying practical consequences for litigation.</p><div className="actions"><a className="button gold" href="/research-notes/possession-without-title">Read the latest note</a><a className="button line" href="/research-index">Explore the research index</a></div></div><aside className="hero-docket"><div className="docket-head"><span>LATEST NOTE</span><b>001</b></div><p className="smallcaps">LAND & PROPERTY · SUPREME COURT</p><h2>Possession Without Title</h2><p>What the Supreme Court actually decided in <i>Oluwi v Eniola</i> and <i>Nwosu v Otunola</i>.</p><div className="citation">(1967) NMLR 339 at 340<br/>(1974) 4 SC 21</div><a href="/research-notes/possession-without-title">Examine the authority →</a></aside></section>
  <section className="question"><div className="section-no">01</div><div><p className="eyebrow">OUR EDITORIAL QUESTION</p><h2>What exactly does this authority support—and how far can counsel safely take it?</h2></div><p>Legal propositions travel quickly. Their factual conditions, limits and judicial context often do not. Our work restores that context.</p></section>
  <section className="wrap section"><div className="section-head"><div><p className="eyebrow">FEATURED RESEARCH</p><h2>One question. The authorities behind it.</h2></div><a href="/research-notes">View all notes →</a></div><div className="feature-grid"><NoteCard/><div className="finding"><p className="eyebrow">THE SHORT ANSWER</p><p className="large">Trespass protects possession, not ownership in the abstract.</p><p>A claimant may succeed against a wrongdoer who cannot establish a better right—even where declaration of title fails. But possession, identity of the land and wrongful interference must still be proved.</p><div className="rule"><span>KEY DISTINCTION</span><b>Ownership ≠ Possession</b></div></div></div></section>
  <section className="dark-section"><div className="wrap"><div className="section-head light"><div><p className="eyebrow">CITATION CHECK</p><h2>A small error can carry a large argument.</h2></div><a href="/citation-check">Open Citation Check →</a></div><div className="correction"><div><span>AS SUPPLIED</span><del>Oluwi v Eniola (1967) NMLR 3390 at 340</del></div><div className="arrow">→</div><div><span>VERIFIED</span><ins>Oluwi v Eniola (1967) NMLR 339 at 340</ins></div></div><p className="correction-note">The reference to Ogbuagu JSC belongs to the later decision in <i>Echere v Ezirike</i>—not to the original 1974 panel in <i>Nwosu v Otunola</i>.</p></div></section>
  <section className="wrap section"><div className="section-head"><div><p className="eyebrow">DOCTRINAL TRAIL</p><h2>Possession and trespass in Nigerian land law</h2></div><a href="/doctrinal-trails/possession-and-trespass">Follow the trail →</a></div><div className="timeline"><div><b>1967</b><span>Oluwi v Eniola</span><small>Independent remedies</small></div><div><b>1974</b><span>Nwosu v Otunola</span><small>Comparative possession</small></div><div><b>2006</b><span>Echere v Ezirike</span><small>Modern restatement</small></div><div className="pending"><b>NEXT</b><span>Later treatment</span><small>Editorial development</small></div></div></section>
  <section className="topics"><div className="wrap"><div className="section-head"><div><p className="eyebrow">BROWSE BY SUBJECT</p><h2>A growing map of Nigerian doctrine</h2></div><a href="/topics">All topics →</a></div><div className="topic-grid">{topics.map(([n,d,c],i)=><a href={`/topics/${n.toLowerCase().replaceAll(" & ","-").replaceAll(" ","-")}`} key={n}><span>0{i+1}</span><h3>{n}</h3><p>{d}</p><b>{c} notes →</b></a>)}</div></div></section>
  <section className="digest"><div><p className="eyebrow">THE WEEKLY DIGEST</p><h2>One legal question.<br/>Carefully examined.</h2><p>Receive the short holding, the important limitation and a link to the complete Research Note.</p></div><form><label>Email address<input type="email" placeholder="you@chambers.com"/></label><button type="button">Join the digest</button><small>Demo form — mailing integration will be connected before launch.</small></form></section>
  <section className="wrap commission"><p className="eyebrow">PROFESSIONAL INSTRUCTIONS</p><h2>Need the authorities examined in the context of a live matter?</h2><p>Magaji Law accepts selected instructions for legal research, litigation support and advisory opinions, subject to conflict checking and formal acceptance.</p><a className="button navy" href="/commission-research">Commission legal research</a></section>
  </Shell>}

function Notes(){return <Shell><PageHero eyebrow="THE PUBLICATION ARCHIVE" title="Magaji Law Research Notes" dek="Numbered examinations of Nigerian judicial authorities, their limits and their practical use."/><section className="wrap section"><ResearchSearch/></section></Shell>}

function ResearchNote({slug}:{slug:string}){const n=notes.find(x=>x.slug===slug); if(!n)return <NotFound/>; if(n.status==="Forthcoming")return <Shell><PageHero eyebrow={`RESEARCH NOTE ${String(n.issue).padStart(3,"0")} · FORTHCOMING`} title={n.title} dek={n.subtitle}/><section className="wrap narrow section"><div className="notice"><b>Editorial preview</b><p>This note is in development. No unverified holdings, citations or analysis have been published.</p></div><p className="large">{n.abstract}</p><a className="button navy" href="/research-notes">Return to the archive</a></section></Shell>;
return <Shell><article className="article"><div className="article-head"><div className="wrap narrow"><p className="eyebrow">MAGAJI LAW RESEARCH NOTE {String(n.issue).padStart(3,"0")}</p><div className="labels">{n.labels.map(x=><Label key={x}>{x}</Label>)}</div><h1>{n.title}</h1><p className="dek">{n.subtitle}</p><div className="meta"><span>Published {n.published}</span><span>Law checked {n.checked}</span><span>12 min read</span></div><div className="actions"><a className="button gold" href={n.pdf} download>Download PDF</a><span className="button line">Print-ready page</span></div></div></div>
<div className="wrap article-grid"><aside className="toc"><b>ON THIS PAGE</b>{["Question presented","Short answer","Verified authorities","Material facts","What the Court decided","Ogbuagu JSC attribution","Consolidated propositions","Practical use","Limits","Courtroom formulation"].map((x,i)=><a href={`#s${i+1}`} key={x}>{x}</a>)}</aside><div className="prose">
<section id="s1"><h2>Question presented</h2><p>Can a claimant who fails to obtain a declaration of title nevertheless succeed in trespass, and what must that claimant prove?</p></section>
<section id="s2" className="answer"><p className="eyebrow">SHORT ANSWER</p><p>Yes. Trespass to land protects possession rather than ownership in the abstract. A claimant who establishes actual or legally cognisable possession may maintain trespass against a defendant who cannot establish a better title or superior right to possession.</p></section>
<section id="s3"><h2>Verified authorities</h2><div className="authority-table"><div><b>Oluwi v Eniola</b><span>(1967) NMLR 339 at 340</span></div><div><b>Nwosu v Otunola</b><span>(1974) 4 SC 21<br/>(1974) 1 All NLR (Pt. 1) 533</span></div><div><b>Echere v Ezirike</b><span>(2006) 12 NWLR (Pt. 994) 386<br/>(2006) LPELR-1001(SC)</span></div></div></section>
<section id="s4"><h2>Material facts</h2><h3>Oluwi v Eniola</h3><p>The plaintiff sought declaration of title, damages for trespass and an injunction. The declaration failed because the area allegedly granted had not been sufficiently established. The Supreme Court nevertheless treated trespass as a separate inquiry into possession and wrongful interference.</p><h3>Nwosu v Otunola</h3><p>The dispute concerned premises at No. 42A Bale Street, Aiyetoro, Ajegunle, Apapa. The plaintiff sought recovery of possession, mesne profits or damages and an injunction. The controversy required close attention to the comparative strength of the parties’ possessory claims.</p></section>
<section id="s5"><h2>What the Court decided</h2><p>A claim in trespass is not dependent upon success in a declaration-of-title claim. The controlling inquiry is whether the claimant possessed the relevant land before the interference and whether the defendant can demonstrate a better entitlement.</p><p>An injunction presents an additional problem. The land must be sufficiently identified, and the claimant must retain a continuing interest requiring prospective protection.</p></section>
<section id="s6"><h2>The Ogbuagu JSC attribution</h2><div className="citation-check"><b>The attribution requires correction.</b><p>Ogbuagu JSC did not sit in <i>Nwosu v Otunola</i>. The likely source is the later judgment in <i>Echere v Ezirike</i>, where His Lordship cited and applied both older authorities.</p></div></section>
<section id="s7"><h2>Consolidated propositions</h2><ol>{["Trespass is an injury to possession.","Trespass and declaration of title are distinct remedies.","Failure of declaration does not automatically defeat trespass.","Possession must still be proved by credible evidence.","The claimant must identify the land and the defendant’s interference.","Better title or a superior immediate right may defeat the claim.","Injunction requires certainty and a continuing interest.","Success in trespass is not necessarily a declaration of absolute ownership."].map(x=><li key={x}>{x}</li>)}</ol></section>
<section id="s8"><h2>Practical litigation use</h2><p>Evidence of possession may include occupation, cultivation, construction, boundary maintenance, tenancy, receipt of rents, installation of caretakers, permission granted to users or other acts appropriate to the character of the land.</p><p>The pleading should connect those acts to the particular land and state how and when the defendant interfered without consent or lawful authority.</p></section>
<section id="s9"><h2>Limits of the authority</h2><div className="limits"><div><b>A bare assertion is insufficient.</b><p>Possession must be established through credible evidence.</p></div><div><b>The land must be certain.</b><p>Unclear boundaries may defeat relief, particularly an injunction.</p></div><div><b>Better title remains decisive.</b><p>The court may investigate title to determine the superior possessory right.</p></div><div><b>Trespass is not declaration.</b><p>A possessory judgment does not necessarily establish ownership against the world.</p></div></div></section>
<section id="s10"><h2>Suggested courtroom formulation</h2><blockquote>It is settled law that trespass to land is essentially an injury to possession. Accordingly, a claimant who establishes actual or legally cognisable possession may maintain an action in trespass against every person who cannot show a better title or superior right to possession. A claim in trespass is independent of a claim for declaration of title, and failure of the latter does not, without more, occasion failure of the former. See <i>Oluwi v Eniola</i> (1967) NMLR 339 at 340; <i>Nwosu v Otunola</i> (1974) 4 SC 21; (1974) 1 All NLR (Pt. 1) 533; and <i>Echere v Ezirike</i> (2006) 12 NWLR (Pt. 994) 386.</blockquote><p className="caution">Counsel should verify quotations and pinpoint references against the authorised reports before filing.</p></section>
<div className="author"><span className="portrait">PM</span><div><b>Paul Ajeh Magaji, Esq.</b><p>Legal practitioner and Editor, Magaji Law Research · SCN 099793 · Lafia, Nasarawa State.</p></div></div>
</div></div></article></Shell>}

function Index(){return <Shell><PageHero eyebrow="AUTHORITY RETRIEVAL" title="Research Index" dek="Search cases, citations, issues and editorial treatment across the growing Magaji Law Research collection."/><section className="wrap section"><ResearchSearch/><div className="index-note"><b>Index development</b><p>The initial index uses structured local data and is ready to migrate to a database as the collection grows.</p></div></section></Shell>}
function CitationCheck(){return <Shell><PageHero eyebrow="EDITORIAL DESK" title="Citation Check" dek="Correcting miscitation, attribution errors and propositions that travel farther than the judgments supporting them."/><section className="wrap section"><div className="correction light-correction"><div><span>AS SUPPLIED</span><del>(1967) NMLR 3390 at 340</del></div><div className="arrow">→</div><div><span>VERIFIED</span><ins>(1967) NMLR 339 at 340</ins></div></div><div className="two-col"><div><h2>Why it matters</h2><p>A typographical error may look small, but an incorrect citation wastes the court’s time, weakens confidence in an argument and can conceal a deeper misunderstanding of the authority.</p></div><div><h2>Attribution check</h2><p>Ogbuagu JSC cited the older authorities in <i>Echere v Ezirike</i>. He did not sit on the 1974 panel in <i>Nwosu v Otunola</i>.</p></div></div><NoteCard/></section></Shell>}
function Trails({detail=false}:{detail?:boolean}){return <Shell><PageHero eyebrow="CONNECTED AUTHORITIES" title={detail?"Possession and Trespass in Nigerian Land Law":"Doctrinal Trails"} dek={detail?"How a possessory principle travels across decades of Supreme Court authority.":"Follow a legal proposition from its originating authority through restatement, limitation and modern application."}/><section className="wrap section"><div className="timeline vertical"><div><b>1967</b><span>Oluwi v Eniola</span><small>Declaration, trespass and injunction separated</small></div><div><b>1974</b><span>Nwosu v Otunola</span><small>Comparative possession and better title</small></div><div><b>2006</b><span>Echere v Ezirike</span><small>Possession reaffirmed as the foundation</small></div><div className="pending"><b>NEXT</b><span>Later judicial treatment</span><small>Editorial development pending</small></div></div>{!detail&&<a className="button navy" href="/doctrinal-trails/possession-and-trespass">Open the trail</a>}{detail&&<div className="notice"><b>Editorial scope</b><p>The completed trail will examine possession, independence from declaration, comparative rights, better title, identity of land and the conditions for injunctive relief. Unresearched later treatment is not represented as complete.</p></div>}</section></Shell>}
function Topics({slug}:{slug?:string}){const title=slug?slug.split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" "):"Topics";return <Shell><PageHero eyebrow="SUBJECT DIRECTORY" title={title} dek={slug?"Research Notes and doctrinal trails connected to this subject.":"Browse Nigerian judicial doctrine by practice area and recurring legal problem."}/><section className="wrap section"><div className="topic-grid">{topics.map(([n,d,c],i)=><a href={`/topics/${n.toLowerCase().replaceAll(" & ","-").replaceAll(" ","-")}`} key={n}><span>0{i+1}</span><h3>{n}</h3><p>{d}</p><b>{c} notes →</b></a>)}</div>{slug&&<div className="section"><NoteCard/></div>}</section></Shell>}
function Methodology(){const steps=["Verify the identity and citation of the authority.","Establish the court, panel, date and procedural history.","Identify the questions actually determined.","Separate material facts from background facts.","Distinguish ratio, obiter, concurrence and dissent.","Trace earlier authorities relied upon.","Investigate later judicial treatment.","Identify pleading, evidential and procedural consequences.","State the limits of the proposition.","Record corrections transparently."];return <Shell><PageHero eyebrow="EDITORIAL STANDARDS" title="Research methodology" dek="A disciplined process for turning reported decisions into reliable, practical legal intelligence."/><section className="wrap narrow section"><div className="method-list">{steps.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><p>{x}</p></div>)}</div><blockquote>A case merits publication where it corrects an error, resolves confusion, exposes a limitation, connects divided authorities or materially improves how counsel approaches a legal problem.</blockquote><h2>Source and copyright policy</h2><p>Magaji Law Research publishes original analysis and synthesis. It does not reproduce proprietary headnotes, republish subscription law reports or present itself as a substitute for authorised reports. Judicial language is distinguished from editorial analysis, and readers are encouraged to verify authorities before filing.</p></section></Shell>}
function Commission(){return <Shell><PageHero eyebrow="PROFESSIONAL INSTRUCTIONS" title="Commission legal research" dek="Selected research, litigation-support and advisory instructions, grounded in careful treatment of Nigerian authorities."/><section className="wrap section form-grid"><div><h2>Areas of support</h2><ul className="service-list">{["Legal research memoranda","Review and reconciliation of authorities","Written-address research support","Appellate research","Case-law updates","Doctrinal surveys","Institutional legal opinions","Customised legal training"].map(x=><li key={x}>{x}</li>)}</ul><div className="notice"><b>Confidentiality caution</b><p>Do not submit privileged, highly sensitive or time-critical material through this preliminary form. Submission does not create a solicitor-client relationship.</p></div></div><form className="intake"><label>Name<input/></label><label>Organisation or chambers<input/></label><div className="form-row"><label>Email<input type="email"/></label><label>Phone<input type="tel"/></label></div><label>Subject area<input/></label><div className="form-row"><label>Court or jurisdiction<input/></label><label>Deadline<input type="date"/></label></div><label>Brief description<textarea rows={5}/></label><label className="check"><input type="checkbox"/> I acknowledge that the instruction is subject to conflict checking and formal acceptance.</label><button type="button">Prepare enquiry</button><small>Demo form — secure submission handling must be connected before public launch.</small></form></section></Shell>}
function Digest(){return <Shell><PageHero eyebrow="WEEKLY EDITORIAL BRIEF" title="One legal question. Carefully examined." dek="Receive the short holding, the important limitation and a link to the complete Research Note."/><section className="wrap narrow section"><form className="intake"><label>Name<input/></label><label>Email<input type="email"/></label><label>WhatsApp number <span>(optional)</span><input type="tel"/></label><label>Preferred channel<select><option>Email</option><option>WhatsApp</option><option>Both</option></select></label><label className="check"><input type="checkbox"/> I consent to receive the Magaji Law Research digest and understand I may unsubscribe.</label><button type="button">Join the weekly digest</button><small>Demo form — no data is stored until a mailing service is connected.</small></form></section></Shell>}
function About(){return <Shell><PageHero eyebrow="ABOUT THE DESK" title="Legal research as public professional evidence" dek="Magaji Law Research is the research and publishing division of Magaji Law."/><section className="wrap narrow section"><p className="large">The platform examines what Nigerian courts actually decided, how later courts treated those decisions and how counsel may safely apply them.</p><div className="author large-author"><span className="portrait">PM</span><div><h2>Paul Ajeh Magaji, Esq.</h2><p>Legal practitioner and Editor of Magaji Law Research. Supreme Court enrolment number SCN 099793. Based in Lafia, Nasarawa State, Nigeria.</p></div></div><h2>The editorial aim</h2><p>To create a searchable body of original legal scholarship that corrects errors, preserves doctrinal context and improves the practical use of authorities.</p></section></Shell>}
function Policy({kind}:{kind:string}){const copy:Record<string,[string,string,string[]]>= {corrections:["Corrections","Substantive corrections are recorded openly rather than changed silently.",["A correction record identifies its date, affected section and substance.","Minor typographical changes that do not alter meaning may be corrected without a formal notice.","A materially unreliable note may be marked Withdrawn while its record remains visible."]],disclaimer:["Research disclaimer","Professional education and general information—not advice on a particular matter.",["Research Notes do not create a solicitor-client relationship.","Law and judicial treatment may change after the date last checked.","Counsel should verify authorities against authorised reports before filing."]],privacy:["Privacy","A restrained approach to personal information.",["The current demonstration forms do not store or transmit submitted information.","Future integrations should collect only information necessary for the stated purpose.","Sensitive or privileged information should not be sent through general website forms."]],terms:["Terms of use","Conditions governing use of the research platform.",["Original editorial analysis is protected by applicable intellectual-property law.","Fair citation and linking are encouraged; substantial republication requires permission.","The platform must not be represented as an official court or law-reporting service."]]};const [title,dek,items]=copy[kind];return <Shell><PageHero eyebrow="EDITORIAL POLICY" title={title} dek={dek}/><section className="wrap narrow section"><div className="method-list">{items.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><p>{x}</p></div>)}</div></section></Shell>}
function NotFound(){return <Shell><PageHero eyebrow="404" title="The requested page was not found" dek="The research archive may have moved or the address may be incomplete."/><section className="wrap narrow section"><a className="button navy" href="/">Return home</a></section></Shell>}

export function SitePage({path}:{path:string}){
  if(path==="/")return <Home/>;
  if(path==="/research-notes")return <Notes/>;
  if(path.startsWith("/research-notes/"))return <ResearchNote slug={path.split("/").pop()!}/>;
  if(path==="/research-index")return <Index/>;
  if(path==="/citation-check")return <CitationCheck/>;
  if(path==="/doctrinal-trails")return <Trails/>;
  if(path==="/doctrinal-trails/possession-and-trespass")return <Trails detail/>;
  if(path==="/topics")return <Topics/>;
  if(path.startsWith("/topics/"))return <Topics slug={path.split("/").pop()}/>;
  if(path==="/methodology")return <Methodology/>;
  if(path==="/commission-research")return <Commission/>;
  if(path==="/weekly-digest")return <Digest/>;
  if(path==="/about")return <About/>;
  if(["/corrections","/disclaimer","/privacy","/terms"].includes(path))return <Policy kind={path.slice(1)}/>;
  return <NotFound/>;
}
